#!/usr/bin/python
# coding=utf-8
import requests
import unittest
from HTMLTestRunner import HTMLTestRunner
from lxml.html._diffcommand import description


class TestLogin(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.login_url = 'http://lcrmapi.lunztech.cn/api/membership/login?appKey=69800851-4554-4EEC-8D12-E4211B952798'
        cls.username = 'wangxiaowen'
        cls.password = '654321'
    
    @classmethod
    def tearDownClass(cls):
        print('这是所有case的后置条件01')
 
    def setUp(self):
        print('这是每条case的前置条件01')
 
    def tearDown(self):
        print('这是每条case的后置条件01')
 
    def test_01(self): # 测试用例的命名必须以test开头，否则不予执行
        print('01: 第一条case')    
    
    #登录成功,执行结果为：Pass
    def test_login_01(self):
        """
        测试登录
        """
        data = {
            'username': self.username,
            'password': self.password
        }
        response = requests.post(self.login_url, data=data).json()

        assert response['Success'] == True
        print(response['Success'] == True)
        print(response)
        print(type(response))
    
    #登录成功，但是assert结果判定错误，执行结果为:Fail
    def test_login_02(self):

        data = {
            'username': self.username,
            'password': self.password
        }
        response = requests.post(self.login_url, data=data).json()

        assert response['Success'] == False
    
    #登录成功，但是assert处的代码有误，执行结果为：Error
    def test_login_03(self):

        data = {
            'username': self.username,
            'password': self.password
        }
        response = requests.post(self.login_url, data=data).json()

        assert response['Success'] == false
    
    
if __name__ == '__main__':
     
    ftp=open('D:\HTML\wxwtestresult.html','wb')
    #ftp=open('./result/wxwtestresult.html','wb')
    suite = unittest.TestSuite()
    suite.addTest(TestLogin('test_01'))
    suite.addTest(TestLogin('test_login_01'))
    suite.addTest(TestLogin('test_login_02'))
    suite.addTest(TestLogin('test_login_03'))
    runner=HTMLTestRunner(stream=ftp,verbosity=1,title='welcome to this web',description='测试结果集')
    result=runner.run(suite)
#     print(result)
    unittest.main()
    ftp.close()


    

#     suite = unittest.TestSuite()
#     suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestLogin))
#     filename = 'D:\HTML\wxwtest.html'
#     fp = open(filename,'w')
#     runner = HTMLTestRunner(
#         stream = fb,
#         title = 'TestResult',
#         description = 'TestCaseRunResult',
#         verbosity=1
#         )
#     runner.run(suite)
#     fb.close()
    
#     with open(filename, 'wb') as f:
#         runner = HTMLTestRunner(stream=f,
#                                 title='WXW Test Report',
#                                 description='generated by HTMLTestRunner.',
#                                 verbosity=2
#                                 )
#         runner.run(suite)
#         
#     f.close()